unique_ids:
  assets:
    dashboard.html: FG7HF3OKH3FAX5UG5FDX2FHV4OB7JFBE
    single-column.html: 2MQTBZMG2GMXTU2MLETEY32U4CNFSQNK
    theme.css: YX6YCGB2UJEXVBXNY7GWI7TK4MYYAUMD
  forms:
    page_natip: '1757490289041624701732290.6554'
    page_natip.RowTemplate1: '1757490384417386792814423.6463'
  modules: {}
  scripts: {}
  server_modules: {}
